name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - run: make update
      
      - run: make
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: build_release/bin/

  
