name: Build Release

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: git submodule update --init --recursive
      - name: Copy files to env.APK_BUILD_DIR
        run: cd
      - name: SVN and cd to work dir
        run: |
          mkdir ../lib
          svn co https://svn.blender.org/svnroot/bf-blender/tags/blender-3.6-release/lib/win64_vc15/ ../lib/win64_vc15
      - run: mkdir ../build_release
      - run: ls
      - run: ./make.bat update
      
      - run: ./make.bat
      - run: ls
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: build_windows/bin/

  
