name: Build Release

on:
  workflow_dispatch:

env:
  APK_BUILD_DIR: "/tmp/build"
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: git submodule update --init --recursive
      - name: Copy files to env.APK_BUILD_DIR
        run: |
          mkdir -p $APK_BUILD_DIR/blender
          cp -r . $APK_BUILD_DIR/blender
          cd $APK_BUILD_DIR
      - name: SVN and cd to work dir
        run: |
          mkdir lib
          svn co https://svn.blender.org/svnroot/bf-blender/tags/blender-3.6-release/lib/win64_vc15/ lib/
          cd blender
      - run: ls
      - run: ./make.bat update
      
      - run: ./make.bat
      - run: ls
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: build_release/bin/

  
